### PR TITLE
Add missing io import

### PR DESCRIPTION
**Pull request by NebraskaCoder**
Receiving an error in rx.py that io is not defined. Importing it in rx.py fixed the error.

### CODE REVIEW

**Comment by boatbod** [comment]
Fixed, thanks!

**Comment by alphafox02** [comment]
@NebraskaCoder Seems like you’re also checking out the same setup as me. Can you try to run your install with the web server flag? It wouldn’t work for me and had some errors. Just curious if you see the same thing (I also had the io issue this morning and manually fixed it).

**Comment by NebraskaCoder** [comment]
@alphafox02 Are you getting the error `osmosdr source_c creation failure`?

**Comment by boatbod** [comment]
Usually this happens when op25 / gr-osmosdr cannot find the rtl device.  
Does it show up in the "lsusb" command?

**Comment by NebraskaCoder** [comment]
Disregard. My error is now this:
```python
Exception while serving /
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/waitress/channel.py", line 349, in service
    task.service()
  File "/usr/lib/python3/dist-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/lib/python3/dist-packages/waitress/task.py", line 477, in execute
    self.write(chunk)
  File "/usr/lib/python3/dist-packages/waitress/task.py", line 330, in write
    channel.write_soon(towrite)
  File "/usr/lib/python3/dist-packages/waitress/channel.py", line 320, in write_soon
    self.outbufs[-1].append(data)
  File "/usr/lib/python3/dist-packages/waitress/buffers.py", line 249, in append
    self.strbuf = strbuf + s
TypeError: can't concat str to bytes
```

**Comment by alphafox02** [comment]
Like Boatmod said, I get the error you first showed when no device is plugged in. I’ll have to check the second error - it’s only when I try to access the web server do I see it in the terminal and nothing loads in the browser. If I run rx.py just in terminal without the web server option it seems okay, but I’m new and still figuring it out. Might take me awhile to report back.

**Comment by boatbod** [comment]
The waitress error is reproducible and relates to python3 binary vs string.  Unfortunately I haven't tracked down exactly what's causing it yet.

**Comment by NebraskaCoder** [comment]
@alphafox02 your error should be easy to fix as it is the dongle as @boatbod said. My new error is something boatbod will have to look at as it is different.

**Comment by alphafox02** [comment]
Yes, no issues with an rtlsdr plugged in. Running the web server option is where I see the same error as you. I’ll check back for updates.

**Comment by boatbod** [comment]
Please pull the update and try it again.

**Comment by NebraskaCoder** [comment]
Looks good! Thanks!

**Comment by NebraskaCoder** [comment]
Opened a new issue so that we can keep this thread closed. #87

**Pull request closed without merging**
