### PR TITLE
DES-OFB support

### PR DESCRIPTION
**Pull request by JoeyAbsi**
DES-OFB decryption support (P25 Phase I)

### CODE REVIEW

**Comment by boatbod** [comment]
> Would it be possible to start splitting these algorithms and their methods in to individual class files? p25_crypt_algs.cc is going to become a maintenance nightmare once AES-256-OFB/0x84 support is added, and some of these routines could be reused elsewhere.

It's been a while since I was in the p25_crypt_algs class, but the intent has always been that it would be the entry point to decoding, not the meat of the decode algorithms themselves.  Think of it similar to the way rx_sync reassembles frames and then passes the frame on to the decoder (i.e. p25p1, p25p2, dmr, ...).

**Comment by JoeyAbsi** [comment]
Created a class for DES, let the fun begin!

**Comment by boatbod** [comment]
Apologies for the delay in merging the pull request - I'll see if I can eek out some time this weekend to take a peek.
Graham

**Comment by JoeyAbsi** [comment]
> Nice!! Thank you for doing that. As a side note, when's AES-256-OFB support coming? 🤪

AES should be fairly easy to implement, the algorithm has been around for years and is well described in TIA-102.AAAD (test vectors are also provided). The same goes for 3DES (TDEA).

**Comment by boatbod** [comment]
I pulled the merge into 'dev' but it's not building.  Haven't had time to troubleshoot, but please check for missing files.
[code]
In file included from /home/gnorbury/op25/op25/gr-op25_repeater/lib/p25_frame_assembler_impl.cc:26:
/home/gnorbury/op25/op25/gr-op25_repeater/lib/p25_frame_assembler_impl.h:24:10: fatal error: gnuradio/op25_repeater/p25_frame_assembler.h: No such file or directory
   24 | #include <gnuradio/op25_repeater/p25_frame_assembler.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/build.make:154: op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/p25_frame_assembler_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:795: op25/gr-op25_repeater/lib/CMakeFiles/gnuradio-op25_repeater.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
[/code]

**Comment by JoeyAbsi** [comment]
Yes I can confirm I did the development around the gr310 branch which does include the "gnuradio" folder between "include" and "op25_repeater". My guess would be to remove that folder name in the include

**Comment by boatbod** [comment]
I've made changes to the dev branch code (multi_rx,py, tk_p25.py, p25_frame_assembler_impl.h) to make it work under gr-3.8.  It's still going to need to be merged forward into the head and gr310 branches.

**Comment by JoeyAbsi** [comment]
Sounds good, everything is working normally in my environment (gr310) so gr310 should be identical to the PR files. As for gr-3.8, we're you finally able to build everything?

**Comment by boatbod** [comment]
Thank you!
I did run into some problems with changes in line endings that caused 
merge problems, but running the affected files through dos2unix fixed 
that up.  As of right now I've got all your code pushed through to the 
gr310 branch.

**Pull request merged**
